### ISSUE TITLE
打包运行与Editor下 运行不一致

### ISSUE THREAD

**Issue by cocochengang** [chexiongsheng/puerts_fps_demo#2]
用的UE4.26，跟着步骤，把编辑器下的过程走完了，接着打包 WindowsNoEditor 运行没崩溃，但不一致，无法行走转向、Fire...
Log里也没Error的信息提示

**Comment by cocochengang** [comment]
后来在 Saved\Config\WindowsNoEditor 文件Puerts.ini，加了

[/Script/Puerts.PuertsSetting]
AutoModeEnable=True

**Comment by chexiongsheng** [comment]
puerts只是按ue的规则添加了配置，按道理编辑器的配置应该同步到打包后的程序。而且这个配置在手机打包是能同步的。感觉是UE打包程序的问题。

**Comment by cocochengang** [comment]
嗯，同样的UE4.26，我另一个电脑  Saved\Config\WindowsNoEditor   Puerts.ini   AutoModeEnable=True，运行结果还是不一样

**Comment by chexiongsheng** [comment]
按你的描述，就是puerts组件还没启动。之前有人碰到这样的问题，打包后手动改配置就可以了

**Comment by cocochengang** [comment]
请问下，这个配置是啥，能详细指点下么？没找着这方面的描述

**Comment by chexiongsheng** [comment]
你更新到最新的代码，有可能解决了

**Comment by cocochengang** [comment]
嗯，都正常了，真不错！谢谢哈
