### ISSUE TITLE
ue4 4.24  切换保存后页面无法刷新 新的staticMesh

### ISSUE THREAD

**Issue by ooijopk** [chexiongsheng/puerts_fps_demo#3]
![image](https://user-images.githubusercontent.com/73647670/145346004-99eab46e-ad7b-404d-990c-93cd205af661.png)
不知道啥原因
![image](https://user-images.githubusercontent.com/73647670/145346318-072756d5-b49e-407f-b143-452019a9de25.png)
vs重新启动后才能看到最新的staticMesh
是不是之后ts那边改了任何东西都需要重启vs呢

**Comment by chexiongsheng** [comment]
应该不用阿，甚至正在play都可以运行时生效

**Comment by ooijopk** [comment]
你好，我又试了一下，问题还在，无法动态生效，你那边正常的话就说明是我这里操作有问题，暂时无法查明啥原因，我只能继续找问题所在
![image](https://user-images.githubusercontent.com/73647670/145531265-7f99ae94-c4e7-4eb5-ae6e-1e62a5584001.png)
